### PR TITLE
use reusable workflows

### PR DESCRIPTION
**Pull request by mcred**

### CODE REVIEW

**Comment by jnewton03** [comment]
@mcred do we want to add a dependabot.yml and CODEOWNERS file as part of this or in a separate PR?

**Comment by jnewton03** [comment]
> @jnewton03 If they are ready to go, please add them to this PR!

@mcred Done!

**Review by jnewton03 — APPROVED** [review]
LGTM! 🚀

**Comment by jnewton03** [comment]
@kevin-atx this PR updates the extension repo template with:
- reusable workflows
- dependabot config
- CODEOWNERS file with Nathan as the only reviewer

**Comment by jnewton03** [comment]
@mcred anything else to do on this?

**Comment by mcred** [comment]
@jnewton03 It needs some updates to inherit secrets and pin a release version of the build logic. Update coming soon.

**Pull request merged**
